// Code generated by 'yaegi extract github.com/zbysir/writeflow/pkg/plugin'. DO NOT EDIT.

package gosymbols

import (
	"context"
	"github.com/zbysir/writeflow/pkg/plugin"
	"reflect"
)

func init() {
	Symbols["github.com/zbysir/writeflow/pkg/plugin/plugin"] = map[string]reflect.Value{
		// type definitions
		"CMDer":            reflect.ValueOf((*plugin.CMDer)(nil)),
		"Category":         reflect.ValueOf((*plugin.Category)(nil)),
		"Component":        reflect.ValueOf((*plugin.Component)(nil)),
		"ComponentData":    reflect.ValueOf((*plugin.ComponentData)(nil)),
		"ComponentSource":  reflect.ValueOf((*plugin.ComponentSource)(nil)),
		"Locales":          reflect.ValueOf((*plugin.Locales)(nil)),
		"Module":           reflect.ValueOf((*plugin.Module)(nil)),
		"ModuleInfo":       reflect.ValueOf((*plugin.ModuleInfo)(nil)),
		"ModuleRegister":   reflect.ValueOf((*plugin.ModuleRegister)(nil)),
		"NodeAnchorTarget": reflect.ValueOf((*plugin.NodeAnchorTarget)(nil)),
		"NodeInputParam":   reflect.ValueOf((*plugin.NodeInputParam)(nil)),
		"NodeOutputAnchor": reflect.ValueOf((*plugin.NodeOutputAnchor)(nil)),

		// interface wrapper definitions
		"_CMDer":          reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_CMDer)(nil)),
		"_Module":         reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_Module)(nil)),
		"_ModuleRegister": reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_ModuleRegister)(nil)),
	}
}

// _github_com_zbysir_writeflow_pkg_plugin_CMDer is an interface wrapper for CMDer type
type _github_com_zbysir_writeflow_pkg_plugin_CMDer struct {
	IValue interface{}
	WExec  func(ctx context.Context, params map[string]interface{}) (rsp map[string]interface{}, err error)
}

func (W _github_com_zbysir_writeflow_pkg_plugin_CMDer) Exec(ctx context.Context, params map[string]interface{}) (rsp map[string]interface{}, err error) {
	return W.WExec(ctx, params)
}

// _github_com_zbysir_writeflow_pkg_plugin_Module is an interface wrapper for Module type
type _github_com_zbysir_writeflow_pkg_plugin_Module struct {
	IValue      interface{}
	WCategories func() []plugin.Category
	WCmd        func() map[string]plugin.CMDer
	WComponents func() []plugin.Component
	WInfo       func() plugin.ModuleInfo
}

func (W _github_com_zbysir_writeflow_pkg_plugin_Module) Categories() []plugin.Category {
	return W.WCategories()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Module) Cmd() map[string]plugin.CMDer {
	return W.WCmd()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Module) Components() []plugin.Component {
	return W.WComponents()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Module) Info() plugin.ModuleInfo {
	return W.WInfo()
}

// _github_com_zbysir_writeflow_pkg_plugin_ModuleRegister is an interface wrapper for ModuleRegister type
type _github_com_zbysir_writeflow_pkg_plugin_ModuleRegister struct {
	IValue          interface{}
	WRegisterModule func(m plugin.Module)
}

func (W _github_com_zbysir_writeflow_pkg_plugin_ModuleRegister) RegisterModule(m plugin.Module) {
	W.WRegisterModule(m)
}
