// Code generated by 'yaegi extract github.com/zbysir/writeflow/pkg/plugin'. DO NOT EDIT.

package gosymbols

import (
	"context"
	"github.com/zbysir/writeflow/pkg/plugin"
	"reflect"
)

func init() {
	Symbols["github.com/zbysir/writeflow/pkg/plugin/plugin"] = map[string]reflect.Value{
		// type definitions
		"CMDer":            reflect.ValueOf((*plugin.CMDer)(nil)),
		"Category":         reflect.ValueOf((*plugin.Category)(nil)),
		"Component":        reflect.ValueOf((*plugin.Component)(nil)),
		"ComponentData":    reflect.ValueOf((*plugin.ComponentData)(nil)),
		"ComponentSource":  reflect.ValueOf((*plugin.ComponentSource)(nil)),
		"Locales":          reflect.ValueOf((*plugin.Locales)(nil)),
		"NodeAnchorTarget": reflect.ValueOf((*plugin.NodeAnchorTarget)(nil)),
		"NodeInputParam":   reflect.ValueOf((*plugin.NodeInputParam)(nil)),
		"NodeOutputAnchor": reflect.ValueOf((*plugin.NodeOutputAnchor)(nil)),
		"Plugin":           reflect.ValueOf((*plugin.Plugin)(nil)),
		"PluginInfo":       reflect.ValueOf((*plugin.PluginInfo)(nil)),
		"Register":         reflect.ValueOf((*plugin.Register)(nil)),

		// interface wrapper definitions
		"_CMDer":    reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_CMDer)(nil)),
		"_Plugin":   reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_Plugin)(nil)),
		"_Register": reflect.ValueOf((*_github_com_zbysir_writeflow_pkg_plugin_Register)(nil)),
	}
}

// _github_com_zbysir_writeflow_pkg_plugin_CMDer is an interface wrapper for CMDer type
type _github_com_zbysir_writeflow_pkg_plugin_CMDer struct {
	IValue interface{}
	WExec  func(ctx context.Context, params map[string]interface{}) (rsp map[string]interface{}, err error)
}

func (W _github_com_zbysir_writeflow_pkg_plugin_CMDer) Exec(ctx context.Context, params map[string]interface{}) (rsp map[string]interface{}, err error) {
	return W.WExec(ctx, params)
}

// _github_com_zbysir_writeflow_pkg_plugin_Plugin is an interface wrapper for Plugin type
type _github_com_zbysir_writeflow_pkg_plugin_Plugin struct {
	IValue      interface{}
	WCategories func() []plugin.Category
	WCmd        func() map[string]plugin.CMDer
	WComponents func() []plugin.Component
	WInfo       func() plugin.PluginInfo
}

func (W _github_com_zbysir_writeflow_pkg_plugin_Plugin) Categories() []plugin.Category {
	return W.WCategories()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Plugin) Cmd() map[string]plugin.CMDer {
	return W.WCmd()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Plugin) Components() []plugin.Component {
	return W.WComponents()
}
func (W _github_com_zbysir_writeflow_pkg_plugin_Plugin) Info() plugin.PluginInfo {
	return W.WInfo()
}

// _github_com_zbysir_writeflow_pkg_plugin_Register is an interface wrapper for Register type
type _github_com_zbysir_writeflow_pkg_plugin_Register struct {
	IValue          interface{}
	WRegisterPlugin func(m plugin.Plugin)
}

func (W _github_com_zbysir_writeflow_pkg_plugin_Register) RegisterPlugin(m plugin.Plugin) {
	W.WRegisterPlugin(m)
}
